from pathlib import Path
p=Path(__file__).resolve().parents[2]/'context/scripts/build_triangle_site.py'
s=p.read_text()
start=s.index('area_details = {' if 'area_details = {' in s else 'for name, slug, angle in areas:')
end=s.index('service_details = {', start)
new = r'''area_details = {
    'raleigh-nc': ('Capital-city polish without the corporate fog.', 'Raleigh buyers often compare several providers, check reviews, scan the website, and look for signs that the business is organized enough to trust.', ['clear service explanations for Raleigh searchers', 'local proof that fits capital-city and professional-service expectations', 'GBP, citations, and service pages that reinforce the same message'], ['home services near fast-growing neighborhoods', 'professional and appointment-based services', 'healthcare-adjacent and local specialty providers']),
    'durham-nc': ('Useful, direct, and credible beats polished-but-empty.', 'Durham buyers tend to reward businesses that explain things plainly, show real usefulness, and avoid overproduced agency language.', ['content that sounds specific instead of generic', 'AI-ready FAQs built around real buyer questions', 'local SEO signals that connect Durham services, neighborhoods, and intent'], ['contractors and home services', 'wellness, clinic-adjacent, and appointment businesses', 'local professional services with a practical edge']),
    'cary-nc': ('High-expectation buyers need fast clarity.', 'Cary has a practical, quality-conscious buyer base. People expect the business to look current, organized, and easy to contact from mobile.', ['mobile-first service pages with strong trust cues', 'clear offer structure for comparison-heavy searches', 'landing pages that support local SEO and Google Ads'], ['premium home services', 'family-focused local services', 'professional providers competing on trust and responsiveness']),
    'chapel-hill-nc': ('Thoughtful credibility matters here.', 'Chapel Hill buyers often respond to calm, informed copy that explains the work without pushing too hard.', ['educational service copy and useful FAQs', 'proof and process sections that reduce uncertainty', 'structured content that supports search, maps, and AI summaries'], ['health, wellness, and clinic-adjacent services', 'professional services', 'specialty contractors and local experts']),
    'apex-nc': ('Growth-market visibility needs a stronger local signal.', 'Apex is competitive because growth brings more providers, more searches, and more comparison. Thin pages are easy to ignore.', ['service-area content that does more than mention Apex once', 'conversion paths for fast quote and consultation decisions', 'GBP and citation consistency across a growing market'], ['home services and contractors', 'local family-service businesses', 'appointment-based providers serving newer neighborhoods']),
    'morrisville-nc': ('Tech-adjacent buyers expect precision.', 'Morrisville buyers often move quickly, compare digitally, and expect the website to answer obvious questions without friction.', ['precise service pages and fast mobile UX', 'AI-search-ready explanations that define services clearly', 'paid-search landing pages that match high-intent searches'], ['tech-adjacent local services', 'professional services', 'home and property services serving busy households']),
}
for name, slug, angle in areas:
    voice, buyer, strengths, fits = area_details[slug]
    strength_html = ''.join(f'<li>{x}</li>' for x in strengths)
    fit_html = ''.join(f'<li>{x}</li>' for x in fits)
    p = f"""<section class="hero"><div class="wrap"><p class="eyebrow">{name}, {STATE}</p><h1>Clearer digital visibility for {name} service businesses.</h1><p class="lead">{angle} {BRAND} helps {name}-area businesses turn scattered online signals into a clearer website, cleaner local presence, and stronger AI-search-ready explanation of what they do.</p><div class="actions"><a class="btn" href="/contact.html">Talk through {name}</a><a class="btn ghost" href="tel:{PHONE_E164}">Call {PHONE_DISPLAY}</a></div></div></section>
<section class="section"><div class="two"><article class="card"><p class="eyebrow">Local buyer read</p><h2>{voice}</h2><p>{buyer}</p></article><article class="card"><p class="eyebrow">What gets strengthened</p><h2>Better local signals across the whole lead path.</h2><ul>{strength_html}</ul></article></div></section>
<section class="section dark"><div><p class="eyebrow">SEO and AI visibility</p><h2>{name} pages should answer real questions, not just repeat the city name.</h2><div class="cards"><article class="card"><h3>Service clarity</h3><p>We make the page clear about what the business does, who it helps, and which searches should lead to it.</p></article><article class="card"><h3>Local relevance</h3><p>The page connects the service to {name} buyer expectations, nearby demand, and the practical reasons someone would choose the business.</p></article><article class="card"><h3>Answer-ready structure</h3><p>Headings, FAQs, schema, and plain-language explanations help Google, maps, and AI systems understand the business without guessing.</p></article></div></div></section>
<section class="section"><div class="two"><article class="card"><p class="eyebrow">Best-fit businesses</p><h2>Where this page can support real lead flow</h2><ul>{fit_html}</ul></article><article class="card"><p class="eyebrow">How it compounds</p><h2>The area page becomes part of the monthly marketing system.</h2><p>Once the page is live, it can support Google Business Profile activity, internal links, citation consistency, service-page expansion, AI-search clarity, and paid landing-page relevance. It is not a thin location page. It is a local trust asset.</p><a class="btn" href="/contact.html">Build the {name} growth path</a></article></div></section>"""
    ROOT.joinpath('areas', f'{slug}-marketing-agency.html').write_text(layout(f'{name}, NC AI-Ready Marketing Agency | {BRAND}', f'AI-ready website, local SEO, Google Business Profile, Google Ads, and AI search visibility support for {name}, NC service businesses.', p, area_link(name, slug)))

'''
s=s[:start]+new+s[end:]
p.write_text(s)
print('expanded area pages')
